from typing import Awaitable, Callable, Protocol

type RouteMap = dict[str, Callable[[dict], Awaitable[list[tuple[str, bytes]] | None]]]


class Broker(Protocol):
    async def publish(self, topic: str, message: bytes) -> None: ...
    async def listen(self, routes: RouteMap, exit_on_idle: bool = False) -> None: ...
    async def wait_until_idle(self) -> None: ...
    async def stop(self) -> None: ...
